### ISSUE TITLE
avr-g++: error: missing device or architecture after '-mmcu='

### ISSUE THREAD

**Issue by khgm** [steve3d/arduino-vscode#11]
Hi,
[arduino-avr-mega.txt](https://github.com/steve3d/arduino-vscode/files/771868/arduino-avr-mega.txt)

i got that message when i try to compile with fqbn ardunio:avr:mega parameter. I spent several hours to debug where can be the problem without success. Attached the detailed output and parameters.

Thanks for the advice/idea where to dig deeper
Gabor

**Comment by steve3d** [comment]
first, please make sure that you are using arduino ide 1.8+
then you will need to find the missing parameter from Arduino IDE by enabling the verbose output.

**Comment by steve3d** [comment]
and I think for your board, the correct `fqbn` should be set as `arduino:avr:mega:cpu=atmega2560`

**Comment by khgm** [comment]
that fqbn worked, thanks
