### ISSUE TITLE
Using VSCode on Windows 7 - "Can not build anything without Arduino IDE, please update settings."

### ISSUE THREAD

**Issue by iceman198** [steve3d/arduino-vscode#2]
I've set the path my settings.json (the overwrite one anyways)

`"arduino.idePath": "C:\\Program Files (x86)\\Arduino\\"`

I've tried 

`"arduino.idePath": "C:\\Program Files (x86)\\Arduino\\arduino.exe"`

as well...still get this error

**Comment by steve3d** [comment]
build a sketch only need to set ide path, and under that path, there must be arduino-builder.exe file exists.

and also, please update to arduino 1.8.

**Comment by iceman198** [comment]
That was it, thanks!  Was using 1.6.
