### ISSUE TITLE
mac os x issues

### ISSUE THREAD

**Issue by leonardpitzu** [steve3d/arduino-vscode#23]
what's the expected path for macos (sierra)? i've pointed to the .app but alto to the arduino executable yet it only prints error without an actual message. i would expect at least a message telling me that the ide path is wrong or something similar.

**Comment by steve3d** [comment]
you only need to specify the `idePath` if your arduino IDE is not placed in the `/Applications` folder.

if not, you should point to the `Contents/Java` subfolder of `Arduino IDE.app`
