### ISSUE TITLE
NodeMCU / ESP8266 support

### ISSUE THREAD

**Issue by ivaylopivanov** [steve3d/arduino-vscode#6]
As mentioned [here](https://github.com/steve3d/arduino-vscode/issues/4#issuecomment-277454289) it will be nice to have support for other Arduino devices.

**Comment by steve3d** [comment]
sorry, I'm not a master of arduino, and this project is just my hobby project, and also this is very first time I heard of this NodeMCU device.

and I don't have this type of device by hand, so even if I want to support it, I can not do that without a actual device.

So sorry for that.

**Comment by steve3d** [comment]
done, please help me test and give some feedback. thanks

**Comment by guatedude2** [comment]
I noted that after running builds on mac for several times, the `tmp/sketch` gets populated with tmp redundantly so you get
`tmp/sketch/tmp/sketch/...`, so in my script I use `.build/` because `.` files don't get copied over to the sketch

Everything else works perfectly!

**Comment by guatedude2** [comment]
I think this ticket can be closed

**Comment by steve3d** [comment]
You might need to clean or rebuild.

Close this.
